%% ================================================================
% HIFE_3D_Enhanced.m
%
% HIFE | Hierarchical Integrated Flow Electrode
%
% ENHANCED 3-D SCIENTIFIC ARCHITECTURE VISUALIZATION
%
% Visual concept:
%   Exploded hierarchical HIFE architecture with enhanced
%   MATLAB SURF rendering, saturated layer colors, smooth
%   interpolation, metallic highlights, and 3-D depth.
%
% Layer color language:
%   BLUE       = cell-level flow distribution
%   CYAN/BLUE  = hydraulic pathways
%   GREEN      = mesoscale porous network
%   GOLD       = fibrous electrochemical electrode
%   SILVER     = membrane
%
% IMPORTANT:
%   Conceptual / schematic visualization.
%   Not CFD, experimental imaging, measured morphology,
%   or a fabricated prototype.
%
% Author: Umar Tabbsum
% Date: 02 October 2026
%% ================================================================

clear;
close all;
clc;

%% ================================================================
% 1. FIGURE
% ================================================================

W = 1920;
H = 1080;

fig = figure( ...
    'Color',[0.97 0.98 0.99], ...
    'Units','pixels', ...
    'Position',[40 40 W H], ...
    'Renderer','opengl', ...
    'Resize','off');

ax = axes( ...
    'Parent',fig, ...
    'Position',[0.035 0.075 0.93 0.84]);

hold(ax,'on');

axis(ax,'equal');
axis(ax,'off');

set(ax, ...
    'FontName','Arial', ...
    'Projection','perspective');

%% ================================================================
% 2. ENHANCED COLOR SYSTEM
%% ================================================================

% Deep hydraulic blue
BLUE_DARK = [0.015 0.16 0.42];
BLUE      = [0.025 0.38 0.82];
BLUE_L    = [0.20 0.68 0.98];

% Emerald / green porous network
GREEN_DARK = [0.015 0.30 0.18];
GREEN      = [0.02 0.58 0.32];
GREEN_L    = [0.30 0.82 0.50];

% Gold / yellow electrode
GOLD_DARK = [0.62 0.30 0.015];
GOLD      = [0.95 0.58 0.035];
GOLD_L    = [1.00 0.82 0.20];

% Silver / membrane
SILVER_DARK = [0.36 0.40 0.45];
SILVER      = [0.68 0.73 0.79];
SILVER_L    = [0.90 0.93 0.96];

% Text
TEXT_DARK = [0.055 0.075 0.10];

%% ================================================================
% 3. ARCHITECTURE DIMENSIONS
%% ================================================================

Lx = 10;
Ly = 6;

Z_membrane  = 0.00;
Z_fiber     = 1.70;
Z_porous    = 3.55;
Z_hydraulic = 5.40;
Z_cell      = 7.25;

%% ================================================================
% 4. MEMBRANE — SILVER 3-D SURFACE
%% ================================================================

nx = 70;
ny = 50;

[xm,ym] = meshgrid( ...
    linspace(0,Lx,nx), ...
    linspace(0,Ly,ny));

% Very subtle surface curvature for realistic 3-D lighting
zm = Z_membrane + ...
     0.045*sin(2*pi*xm/Lx).*sin(pi*ym/Ly);

% Normalized height used for color interpolation
cm = ...
    0.5 + ...
    0.5*(zm-min(zm(:))) / ...
    max(max(zm(:))-min(zm(:)),eps);

surf(ax,xm,ym,zm,cm, ...
    'FaceColor','interp', ...
    'EdgeColor','none', ...
    'FaceAlpha',0.94, ...
    'FaceLighting','gouraud', ...
    'AmbientStrength',0.32, ...
    'DiffuseStrength',0.78, ...
    'SpecularStrength',0.65, ...
    'SpecularExponent',35);

%% ================================================================
% MEMBRANE EDGE
%% ================================================================

plot3(ax, ...
    [0 Lx Lx 0 0], ...
    [0 0 Ly Ly 0], ...
    Z_membrane*ones(1,5), ...
    '-', ...
    'Color',SILVER_DARK, ...
    'LineWidth',2.2);

%% ================================================================
% 5. FIBROUS ELECTRODE — GOLD
%% ================================================================

rng(7);

Nfibers = 115;

fiberRadius = 0.055;

for i = 1:Nfibers

    x0 = 0.22 + 9.56*rand;
    y0 = 0.22 + 5.56*rand;

    L = 0.90 + 1.65*rand;

    theta0 = ...
        -0.40 + ...
        0.80*rand;

    x1 = x0 + L*cos(theta0);
    y1 = y0 + L*sin(theta0);

    x1 = min(max(x1,0.18),Lx-0.18);
    y1 = min(max(y1,0.18),Ly-0.18);

    t = linspace(0,1,28);

    xc = x0 + (x1-x0)*t;
    yc = y0 + (y1-y0)*t;

    phase = 2*pi*rand;

    xc = xc + ...
        0.045*sin(2*pi*t+phase);

    yc = yc + ...
        0.045*cos(2*pi*t+phase);

    zc = Z_fiber + ...
         0.10*sin(2*pi*t+phase);

    drawEnhancedFiber( ...
        ax, ...
        xc,yc,zc, ...
        fiberRadius, ...
        GOLD_DARK, ...
        GOLD, ...
        GOLD_L);

end

%% ================================================================
% GOLD ACTIVE SURFACE
%% ================================================================

[xa,ya] = meshgrid( ...
    linspace(0,Lx,55), ...
    linspace(0,Ly,40));

za = Z_fiber - 0.095 + ...
     0.018*sin(xa*2).*cos(ya*1.5);

ca = ...
    0.35 + ...
    0.65*(za-min(za(:))) / ...
    max(max(za(:))-min(za(:)),eps);

surf(ax,xa,ya,za,ca, ...
    'FaceColor','interp', ...
    'EdgeColor','none', ...
    'FaceAlpha',0.23, ...
    'FaceLighting','gouraud', ...
    'AmbientStrength',0.35, ...
    'DiffuseStrength',0.75, ...
    'SpecularStrength',0.45, ...
    'SpecularExponent',20);

%% ================================================================
% ELECTRODE FRAME
%% ================================================================

plot3(ax, ...
    [0 Lx Lx 0 0], ...
    [0 0 Ly Ly 0], ...
    Z_fiber*ones(1,5), ...
    '-', ...
    'Color',GOLD_DARK, ...
    'LineWidth',2.0);

%% ================================================================
% 6. MESOSCALE POROUS NETWORK — GREEN
%% ================================================================

rng(21);

Nnodes = 72;

px = 0.35 + (Lx-0.70)*rand(Nnodes,1);
py = 0.35 + (Ly-0.70)*rand(Nnodes,1);

pz = Z_porous + ...
     0.28*(rand(Nnodes,1)-0.5);

%% ================================================================
% NETWORK CONNECTIONS
%% ================================================================

for i = 1:Nnodes

    dx = px-px(i);
    dy = py-py(i);

    d = sqrt(dx.^2 + dy.^2);

    d(i) = inf;

    [~,idx] = sort(d);

    for n = 1:3

        j = idx(n);

        if d(j) < 1.70

            % Alternating green shades
            if mod(i+n,3) == 0
                tubeColor = GREEN_DARK;
            elseif mod(i+n,3) == 1
                tubeColor = GREEN;
            else
                tubeColor = GREEN_L;
            end

            drawEnhancedTube( ...
                ax, ...
                [px(i) py(i) pz(i)], ...
                [px(j) py(j) pz(j)], ...
                0.070, ...
                tubeColor);

        end

    end

end

%% ================================================================
% NETWORK NODES
%% ================================================================

scatter3(ax, ...
    px,py,pz, ...
    22, ...
    GREEN_L, ...
    'filled', ...
    'MarkerEdgeColor',GREEN_DARK, ...
    'LineWidth',0.5);

%% ================================================================
% NETWORK FRAME
%% ================================================================

plot3(ax, ...
    [0 Lx Lx 0 0], ...
    [0 0 Ly Ly 0], ...
    Z_porous*ones(1,5), ...
    '-', ...
    'Color',GREEN_DARK, ...
    'LineWidth',2.0);

%% ================================================================
% 7. HYDRAULIC DISTRIBUTION — BLUE
%% ================================================================

channelY = [0.80 2.20 3.75 5.20];

for k = 1:length(channelY)

    drawEnhancedTube( ...
        ax, ...
        [0.10 channelY(k) Z_hydraulic], ...
        [Lx-0.10 channelY(k) Z_hydraulic], ...
        0.20, ...
        BLUE);

end

%% ================================================================
% VERTICAL MANIFOLDS
%% ================================================================

drawEnhancedTube( ...
    ax, ...
    [0.10 0.80 Z_hydraulic], ...
    [0.10 5.20 Z_hydraulic], ...
    0.20, ...
    BLUE_DARK);

drawEnhancedTube( ...
    ax, ...
    [Lx-0.10 0.80 Z_hydraulic], ...
    [Lx-0.10 5.20 Z_hydraulic], ...
    0.16, ...
    BLUE_L);

%% ================================================================
% HYDRAULIC SURFACE PLATE
%% ================================================================

[xh,yh] = meshgrid( ...
    linspace(0,Lx,65), ...
    linspace(0,Ly,42));

zh = Z_hydraulic - 0.12 + ...
     0.025*sin(xh*1.7).*cos(yh*1.2);

ch = ...
    0.25 + ...
    0.75*(zh-min(zh(:))) / ...
    max(max(zh(:))-min(zh(:)),eps);

surf(ax,xh,yh,zh,ch, ...
    'FaceColor','interp', ...
    'EdgeColor','none', ...
    'FaceAlpha',0.10, ...
    'FaceLighting','gouraud', ...
    'AmbientStrength',0.28, ...
    'DiffuseStrength',0.80, ...
    'SpecularStrength',0.55, ...
    'SpecularExponent',25);

%% ================================================================
% 8. FLOW ARROWS
%% ================================================================

for k = 1:length(channelY)

    quiver3(ax, ...
        0.90, ...
        channelY(k), ...
        Z_hydraulic+0.24, ...
        1.20,0,0, ...
        'Color',BLUE_L, ...
        'LineWidth',3.0, ...
        'MaxHeadSize',0.65);

    quiver3(ax, ...
        3.70, ...
        channelY(k), ...
        Z_hydraulic+0.24, ...
        1.20,0,0, ...
        'Color',BLUE_L, ...
        'LineWidth',3.0, ...
        'MaxHeadSize',0.65);

    quiver3(ax, ...
        6.50, ...
        channelY(k), ...
        Z_hydraulic+0.24, ...
        1.20,0,0, ...
        'Color',BLUE_L, ...
        'LineWidth',3.0, ...
        'MaxHeadSize',0.65);

end

%% ================================================================
% 9. CELL-LEVEL DISTRIBUTION — BLUE / CYAN
%% ================================================================

[xc,yc] = meshgrid( ...
    linspace(0,Lx,65), ...
    linspace(0,Ly,42));

% Slight dome-like engineered surface
zc = Z_cell + ...
     0.08*exp(-((xc-Lx/2).^2 + ...
                 (yc-Ly/2).^2)/10);

cc = ...
    0.15 + ...
    0.85*(zc-min(zc(:))) / ...
    max(max(zc(:))-min(zc(:)),eps);

surf(ax,xc,yc,zc,cc, ...
    'FaceColor','interp', ...
    'EdgeColor','none', ...
    'FaceAlpha',0.72, ...
    'FaceLighting','gouraud', ...
    'AmbientStrength',0.28, ...
    'DiffuseStrength',0.85, ...
    'SpecularStrength',0.70, ...
    'SpecularExponent',35);

%% ================================================================
% CELL DISTRIBUTION RAILS
%% ================================================================

railY = [0.65 1.75 2.85 3.95 5.05];

for k = 1:length(railY)

    drawEnhancedTube( ...
        ax, ...
        [0.25 railY(k) Z_cell+0.10], ...
        [Lx-0.25 railY(k) Z_cell+0.10], ...
        0.070, ...
        BLUE);

end

%% ================================================================
% CELL FRAME
%% ================================================================

plot3(ax, ...
    [0 Lx Lx 0 0], ...
    [0 0 Ly Ly 0], ...
    Z_cell*ones(1,5), ...
    '-', ...
    'Color',BLUE_DARK, ...
    'LineWidth',2.4);

%% ================================================================
% 10. VERTICAL HIERARCHICAL CONNECTIONS
%% ================================================================

connectionX = [1.15 3.45 5.75 8.05];

for k = 1:length(connectionX)

    drawEnhancedTube( ...
        ax, ...
        [connectionX(k) Ly/2 Z_hydraulic+0.10], ...
        [connectionX(k) Ly/2 Z_cell-0.10], ...
        0.038, ...
        BLUE_L);

end

%% ================================================================
% 11. INLET
%% ================================================================

drawEnhancedTube( ...
    ax, ...
    [-1.35 Ly/2 Z_hydraulic], ...
    [0.10 Ly/2 Z_hydraulic], ...
    0.31, ...
    BLUE_DARK);

quiver3(ax, ...
    -1.85,Ly/2,Z_hydraulic, ...
    1.00,0,0, ...
    'Color',BLUE_L, ...
    'LineWidth',4.0, ...
    'MaxHeadSize',0.70);

%% ================================================================
% 12. OUTLET
%% ================================================================

drawEnhancedTube( ...
    ax, ...
    [Lx-0.10 Ly/2 Z_hydraulic], ...
    [Lx+1.35 Ly/2 Z_hydraulic], ...
    0.31, ...
    BLUE_DARK);

quiver3(ax, ...
    Lx+0.75,Ly/2,Z_hydraulic, ...
    1.00,0,0, ...
    'Color',BLUE_L, ...
    'LineWidth',4.0, ...
    'MaxHeadSize',0.70);

%% ================================================================
% 13. INTER-LAYER FLOW INDICATION
%
% Small gold/green/blue directional connectors emphasize the
% hierarchy without adding labels directly to the surfaces.
%% ================================================================

flowX = [2.0 5.0 8.0];

for k = 1:length(flowX)

    % Hydraulic -> porous
    quiver3(ax, ...
        flowX(k), ...
        Ly/2, ...
        Z_hydraulic-0.18, ...
        0,0,-0.55, ...
        'Color',BLUE_L, ...
        'LineWidth',2.2, ...
        'MaxHeadSize',0.50);

    % Porous -> electrode
    quiver3(ax, ...
        flowX(k), ...
        Ly/2, ...
        Z_porous-0.12, ...
        0,0,-0.55, ...
        'Color',GREEN_L, ...
        'LineWidth',2.2, ...
        'MaxHeadSize',0.50);

end

%% ================================================================
% 14. CAMERA
%% ================================================================

view(ax,[-38 27]);

xlim(ax,[-2.15 12.15]);
ylim(ax,[-0.85 6.85]);
zlim(ax,[-0.65 8.15]);

%% ================================================================
% 15. ENHANCED LIGHTING
%% ================================================================

camlight(ax,'headlight');
camlight(ax,'right');
camlight(ax,'left');

lighting(ax,'gouraud');
material(ax,'shiny');

%% ================================================================
% 16. TITLE
%% ================================================================

annotation(fig,'textbox', ...
    [0.055 0.925 0.89 0.045], ...
    'String', ...
    'HIFE | Hierarchical Integrated Flow Electrode', ...
    'FontName','Arial', ...
    'FontSize',29, ...
    'FontWeight','bold', ...
    'Color',TEXT_DARK, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'EdgeColor','none');

%% ================================================================
% 17. SUBTITLE
%% ================================================================

annotation(fig,'textbox', ...
    [0.15 0.892 0.70 0.030], ...
    'String', ...
    'Hierarchical flow distribution, porous transport, and electrochemical reaction', ...
    'FontName','Arial', ...
    'FontSize',14, ...
    'Color',[0.32 0.35 0.39], ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'EdgeColor','none');

%% ================================================================
% 18. LAYER LEGEND
%% ================================================================

annotation(fig,'rectangle', ...
    [0.055 0.025 0.89 0.065], ...
    'FaceColor',[1 1 1], ...
    'FaceAlpha',0.94, ...
    'EdgeColor',[0.82 0.84 0.87], ...
    'LineWidth',0.8);

legendLabels = { ...
    'CELL DISTRIBUTION', ...
    'HYDRAULIC PATHWAYS', ...
    'MESOSCALE NETWORK', ...
    'FIBROUS ELECTRODE', ...
    'MEMBRANE'};

legendColors = { ...
    BLUE, ...
    BLUE_DARK, ...
    GREEN, ...
    GOLD, ...
    SILVER};

legendX = [0.14 0.32 0.50 0.68 0.85];

for k = 1:5

    annotation(fig,'ellipse', ...
        [legendX(k)-0.008 0.044 0.014 0.014], ...
        'FaceColor',legendColors{k}, ...
        'EdgeColor','none');

    annotation(fig,'textbox', ...
        [legendX(k)+0.006 0.039 0.13 0.024], ...
        'String',legendLabels{k}, ...
        'FontName','Arial', ...
        'FontSize',9.0, ...
        'FontWeight','bold', ...
        'Color',TEXT_DARK, ...
        'HorizontalAlignment','left', ...
        'VerticalAlignment','middle', ...
        'EdgeColor','none');

end

%% ================================================================
% 19. DESIGN LOGIC
%% ================================================================

annotation(fig,'textbox', ...
    [0.30 0.855 0.40 0.030], ...
    'String', ...
    'DISTRIBUTE   →   TRANSPORT   →   REACT', ...
    'FontName','Arial', ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'Color',BLUE_DARK, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'EdgeColor','none');

%% ================================================================
% 20. SCOPE NOTE
%% ================================================================

annotation(fig,'textbox', ...
    [0.16 0.005 0.68 0.018], ...
    'String', ...
    'Conceptual schematic — not CFD, experimental imaging, or measured morphology.', ...
    'FontName','Arial', ...
    'FontSize',7.5, ...
    'Color',[0.46 0.48 0.51], ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'EdgeColor','none');

%% ================================================================
% 21. EXPORT
%% ================================================================

set(fig,'Renderer','opengl');

exportgraphics( ...
    fig, ...
    'HIFE_3D_Enhanced.png', ...
    'Resolution',300);

exportgraphics( ...
    fig, ...
    'HIFE_3D_Enhanced.pdf', ...
    'ContentType','vector');

%% ================================================================
% 22. CONFIRMATION
%% ================================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('HIFE ENHANCED 3-D ARCHITECTURE\n');
fprintf('============================================================\n');
fprintf('PNG : HIFE_3D_Enhanced.png\n');
fprintf('PDF : HIFE_3D_Enhanced.pdf\n');
fprintf('Size: %d x %d pixels\n',W,H);
fprintf('Resolution: 300 DPI\n');
fprintf('Rendering: OpenGL + Gouraud lighting\n');
fprintf('Material: Shiny\n');
fprintf('============================================================\n');
fprintf('COLOR SYSTEM\n');
fprintf('  BLUE   = Cell / hydraulic distribution\n');
fprintf('  GREEN  = Mesoscale porous network\n');
fprintf('  GOLD   = Fibrous electrochemical electrode\n');
fprintf('  SILVER = Membrane\n');
fprintf('============================================================\n');
fprintf('Conceptual visualization only.\n');
fprintf('============================================================\n\n');


%% ================================================================
% LOCAL FUNCTION
% ENHANCED 3-D TUBE
%% ================================================================

function drawEnhancedTube(ax,P1,P2,radius,baseColor)

    n = 24;

    P1 = P1(:)';
    P2 = P2(:)';

    d = P2-P1;
    L = norm(d);

    if L < eps
        return;
    end

    d = d/L;

    ref = [0 0 1];

    if abs(dot(d,ref)) > 0.90
        ref = [0 1 0];
    end

    N = cross(d,ref);
    N = N/max(norm(N),eps);

    B = cross(d,N);
    B = B/max(norm(B),eps);

    theta = linspace(0,2*pi,n);

    X = zeros(n,2);
    Y = zeros(n,2);
    Z = zeros(n,2);

    C = zeros(n,2);

    for k = 1:n

        % Smooth radial highlight
        intensity = ...
            0.78 + ...
            0.22*cos(theta(k));

        localColor = min(1,baseColor*intensity + ...
            (1-intensity)*[1 1 1]);

        radial = radius * ...
            (cos(theta(k))*N + ...
             sin(theta(k))*B);

        Q1 = P1 + radial;
        Q2 = P2 + radial;

        X(k,:) = [Q1(1) Q2(1)];
        Y(k,:) = [Q1(2) Q2(2)];
        Z(k,:) = [Q1(3) Q2(3)];

        C(k,:) = mean(localColor);

    end

    surf(ax,X,Y,Z, ...
        'FaceColor',baseColor, ...
        'EdgeColor','none', ...
        'FaceAlpha',0.96, ...
        'FaceLighting','gouraud', ...
        'AmbientStrength',0.24, ...
        'DiffuseStrength',0.85, ...
        'SpecularStrength',0.68, ...
        'SpecularExponent',30);

end


%% ================================================================
% LOCAL FUNCTION
% ENHANCED FIBER
%% ================================================================

function drawEnhancedFiber(ax,xc,yc,zc,radius, ...
    darkColor,baseColor,lightColor)

    n = 14;

    xc = xc(:)';
    yc = yc(:)';
    zc = zc(:)';

    tx = gradient(xc);
    ty = gradient(yc);
    tz = gradient(zc);

    theta = linspace(0,2*pi,n);

    X = zeros(n,length(xc));
    Y = zeros(n,length(xc));
    Z = zeros(n,length(xc));

    for j = 1:length(xc)

        T = [tx(j) ty(j) tz(j)];
        T = T/max(norm(T),eps);

        ref = [0 0 1];

        if abs(dot(T,ref)) > 0.90
            ref = [0 1 0];
        end

        N = cross(T,ref);
        N = N/max(norm(N),eps);

        B = cross(T,N);
        B = B/max(norm(B),eps);

        for k = 1:n

            radial = radius * ...
                (cos(theta(k))*N + ...
                 sin(theta(k))*B);

            X(k,j) = xc(j) + radial(1);
            Y(k,j) = yc(j) + radial(2);
            Z(k,j) = zc(j) + radial(3);

        end

    end

    surf(ax,X,Y,Z, ...
        'FaceColor',baseColor, ...
        'EdgeColor','none', ...
        'FaceAlpha',0.93, ...
        'FaceLighting','gouraud', ...
        'AmbientStrength',0.22, ...
        'DiffuseStrength',0.82, ...
        'SpecularStrength',0.78, ...
        'SpecularExponent',40);

end
