%% HIFE_Figure2_Hydraulic_MonteCarlo.m
% =========================================================================
% HIFE — Hierarchical Integrated Flow Electrode
%
% FIGURE 2: ANALYTICAL / COMPUTATIONAL HYDRAULIC DESIGN-SPACE SCREENING
%
% Four-panel engineering screening figure:
%
%   A — Design assumptions
%   B — Baseline uncertainty
%   C — Architecture comparison
%   D — Parameter sensitivity
%
% -------------------------------------------------------------------------
% EVIDENCE CLASSIFICATION
% -------------------------------------------------------------------------
% This script generates MODEL-BASED DESIGN-SPACE EVIDENCE ONLY.
%
% It does NOT contain:
%   - experimental pressure-drop measurements
%   - experimental electrochemical measurements
%   - field data
%   - CFD results
%   - measured HIFE electrode permeability
%
% The analysis is intended to:
%   1. establish a first-order hydraulic hypothesis for HIFE;
%   2. propagate uncertainty in selected design variables;
%   3. compare a porous baseline with a simplified channel-assisted
%      hydraulic surrogate; and
%   4. identify variables for subsequent experimental validation.
%
% The model does NOT establish:
%   - absolute pump-power savings;
%   - electrochemical utilization;
%   - reaction kinetics;
%   - durability;
%   - manufacturing yield;
%   - stack-level flow distribution;
%   - techno-economic performance.
%
% -------------------------------------------------------------------------
% MODEL BASIS
% -------------------------------------------------------------------------
% POROUS ELECTRODE
%
% Darcy-type hydraulic relationship:
%
%       DeltaP = mu * L * v / k
%
% First-order Carman-Kozeny-type permeability approximation:
%
%       k = df^2 * eps^3 / [180 * (1-eps)^2]
%
% This is used only as a first-order screening approximation.
% Actual fibrous-electrode permeability depends on microstructure,
% fiber orientation, tortuosity, and other geometric characteristics.
%
% CHANNEL
%
% The channel-assisted surrogate represents a fully developed laminar
% 1 mm x 1 mm square flow channel.
%
% Darcy-Weisbach pressure-drop relationship:
%
%       DeltaP_channel =
%           f_D * (L/D_h) * (rho*v^2/2)
%
% For a fully developed laminar square duct:
%
%       f_D * Re_Dh = 56.91
%
% where:
%
%       Re_Dh = rho*v*D_h/mu
%
% The value 56.91 is used as a geometry-specific square-channel
% screening relation, not as a universal laminar-flow constant.
%
% CHANNEL-ASSISTED SURROGATE
%
% The porous-land and channel hydraulic resistances are represented
% as simplified parallel pathways:
%
%       R_eff = 1 / (1/R_land + 1/R_channel)
%
% This is a first-order hydraulic surrogate.
% It is NOT a CFD solution of the final HIFE geometry.
%
% -------------------------------------------------------------------------
% NOMINAL DESIGN INPUTS
% -------------------------------------------------------------------------
% Dynamic viscosity              = 1.5 mPa*s
% Density                         = 1000 kg/m^3
% Porosity                        = 0.90
% Characteristic fiber diameter  = 10 um
% Electrode thickness             = 3 mm
% Cell area                       = 100 cm^2
% Porous land                     = 3 mm
% Flow channel                    = 1 mm x 1 mm square
% Hydraulic diameter              = 1 mm
% f_D * Re_Dh                     = 56.91
%
% -------------------------------------------------------------------------
% MONTE CARLO SETTINGS
% -------------------------------------------------------------------------
% Baseline hydraulic model        = 20,000 samples
% Channel-assisted surrogate      = 4,000 samples
% Sensitivity analysis             = 3,000 samples
% Random seed                      = 7
%
% -------------------------------------------------------------------------
% UNCERTAINTY RANGES
% -------------------------------------------------------------------------
% Viscosity                       = +/-10%
% Porosity                        = 0.88 to 0.92
% Fiber diameter                  = +/-10%
% Electrode / hydraulic length   = +/-10%
%
% Random variables are sampled independently and uniformly over
% the specified ranges.
%
% -------------------------------------------------------------------------
% MODEL EXCLUSIONS
% -------------------------------------------------------------------------
% Compression                    = excluded
% Entrance effects               = excluded
% Gas-phase effects              = excluded
% Clogging                       = excluded
%
% These effects require experimental validation.
%
% -------------------------------------------------------------------------
% AUTHOR / REPRODUCIBILITY
% -------------------------------------------------------------------------
% Author: Umar Tabbsum
% Date:   01 October 2026
% =========================================================================

close all;
clear;
clc;

%% ------------------------------------------------------------------------
% REPRODUCIBILITY
% -------------------------------------------------------------------------

SEED = 7;
rng(SEED,'twister');

AUTHOR      = 'Umar Tabbsum';
DATE_STR    = '01 October 2026';
SCRIPT_NAME = 'HIFE_Figure2_Hydraulic_MonteCarlo.m';

%% ------------------------------------------------------------------------
% MONTE CARLO SETTINGS
% -------------------------------------------------------------------------

N_BASE = 20000;
N_CHAN = 4000;
N_SENS = 3000;

%% ------------------------------------------------------------------------
% NOMINAL PHYSICAL INPUTS
% -------------------------------------------------------------------------

mu0 = 1.5e-3;          % Dynamic viscosity [Pa*s]
rho = 1000;            % Electrolyte density [kg/m^3]

eps0 = 0.90;           % Electrode porosity [-]

df0 = 10e-6;           % Characteristic fiber diameter [m]

L0 = 3e-3;             % Electrode / hydraulic path length [m]

Acell = 100e-4;        % Cell area [m^2] = 100 cm^2

land0 = 3e-3;          % Porous-land length [m]

channel0 = 1e-3;       % Square channel side length [m]

Dh = channel0;         % Hydraulic diameter of 1 mm x 1 mm square duct [m]

% Fully developed laminar square-duct Darcy friction-factor relation.
% This is a geometry-specific screening input.
fRe = 56.91;

%% ------------------------------------------------------------------------
% SCREENING VELOCITY
% -------------------------------------------------------------------------

v_screen = 0.01;       % Characteristic superficial velocity [m/s]

%% ------------------------------------------------------------------------
% UNCERTAINTY RANGES
% -------------------------------------------------------------------------

mu_range = [0.90 1.10] * mu0;

eps_range = [0.88 0.92];

df_range = [0.90 1.10] * df0;

L_range = [0.90 1.10] * L0;

%% ------------------------------------------------------------------------
% FIGURE STYLE
% -------------------------------------------------------------------------

navy  = [0.035 0.10 0.16];
teal  = [0.00  0.48 0.50];
blue  = [0.08  0.40 0.68];
gold  = [0.84 0.60 0.15];
slate = [0.30 0.36 0.42];
light = [0.94 0.97 0.98];
white = [1.00 1.00 1.00];

fig = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',[100 100 1800 1200], ...
    'Renderer','painters', ...
    'InvertHardcopy','off');

layout = tiledlayout(fig,2,2, ...
    'TileSpacing','loose', ...
    'Padding','loose');

%% ========================================================================
% PANEL A — DESIGN ASSUMPTIONS
% ========================================================================

axA = nexttile(layout,1);
hold(axA,'on');

axis(axA,[0 1 0 1]);
axis(axA,'off');

title(axA, ...
    'A   DESIGN ASSUMPTIONS', ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'Color',navy, ...
    'Units','normalized', ...
    'Position',[0.5 1.055 0]);

subtitle(axA, ...
    'Inputs used for first-order hydraulic screening', ...
    'FontSize',8.5, ...
    'Color',slate);

row_y = [ ...
    0.845 ...
    0.785 ...
    0.725 ...
    0.665 ...
    0.605 ...
    0.545 ...
    0.485 ...
    0.425 ...
    0.365 ...
    0.305];

labels = { ...
    'Viscosity', ...
    'Density', ...
    'Porosity', ...
    'Fiber diameter', ...
    'Electrode thickness', ...
    'Cell area', ...
    'Porous land', ...
    'Flow channel', ...
    'Channel relation', ...
    'Monte Carlo'};

values = { ...
    '1.5 mPa·s', ...
    '1000 kg/m³', ...
    '0.90', ...
    '10 µm', ...
    '3 mm', ...
    '100 cm²', ...
    '3 mm', ...
    '1 mm × 1 mm square', ...
    'f_D·Re_Dh = 56.91', ...
    '20,000 / 4,000 / 3,000'};

rectangle(axA, ...
    'Position',[0.00 0.255 0.98 0.625], ...
    'FaceColor','none', ...
    'EdgeColor',[0.75 0.80 0.82], ...
    'LineWidth',0.8);

for i = 1:numel(row_y)

    if mod(i,2) == 0

        rectangle(axA, ...
            'Position',[0.005 row_y(i)-0.023 0.97 0.046], ...
            'FaceColor',light, ...
            'EdgeColor','none');

    end

    text(axA, ...
        0.035, ...
        row_y(i), ...
        labels{i}, ...
        'FontSize',8.1, ...
        'Color',slate, ...
        'VerticalAlignment','middle');

    text(axA, ...
        0.43, ...
        row_y(i), ...
        values{i}, ...
        'FontSize',8.1, ...
        'FontWeight','bold', ...
        'Color',navy, ...
        'VerticalAlignment','middle');

end

rectangle(axA, ...
    'Position',[0.00 0.075 0.98 0.115], ...
    'FaceColor',[0.94 0.98 0.98], ...
    'EdgeColor',teal, ...
    'LineWidth',0.9);

text(axA, ...
    0.035, ...
    0.153, ...
    'EVIDENCE STATUS', ...
    'FontSize',7.5, ...
    'FontWeight','bold', ...
    'Color',teal, ...
    'VerticalAlignment','middle');

text(axA, ...
    0.035, ...
    0.112, ...
    'Model-generated design-space evidence; not experimental validation.', ...
    'FontSize',7.8, ...
    'Color',navy, ...
    'VerticalAlignment','middle');

%% ========================================================================
% PANEL B — BASELINE UNCERTAINTY
% ========================================================================

axB = nexttile(layout,2);
hold(axB,'on');
box(axB,'on');

title(axB, ...
    'B   BASELINE UNCERTAINTY', ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'Color',navy);

subtitle(axB, ...
    sprintf('%d Monte Carlo realizations at v = %.3f m/s', ...
    N_BASE,v_screen), ...
    'FontSize',8.5, ...
    'Color',slate);

% Independent uniform sampling over stated uncertainty ranges.
mu_mc = mu_range(1) + ...
        diff(mu_range).*rand(N_BASE,1);

eps_mc = eps_range(1) + ...
         diff(eps_range).*rand(N_BASE,1);

df_mc = df_range(1) + ...
        diff(df_range).*rand(N_BASE,1);

L_mc = L_range(1) + ...
       diff(L_range).*rand(N_BASE,1);

% First-order Carman-Kozeny-type permeability.
k_mc = ...
    (df_mc.^2 .* eps_mc.^3) ./ ...
    (180 .* (1-eps_mc).^2);

% Darcy-type pressure-drop screening metric.
DP_mc = ...
    mu_mc .* L_mc .* v_screen ./ k_mc;

% Distribution statistics.
medDP = median(DP_mc);
p05 = prctile(DP_mc,5);
p95 = prctile(DP_mc,95);

histogram(axB, ...
    DP_mc, ...
    70, ...
    'Normalization','pdf', ...
    'FaceColor',blue, ...
    'FaceAlpha',0.78, ...
    'EdgeColor','none');

xline(axB, ...
    medDP, ...
    '--', ...
    'Color',gold, ...
    'LineWidth',2.0);

xlabel(axB, ...
    'Pressure-drop screening metric at v = 0.01 m/s (Pa)', ...
    'FontSize',8.5, ...
    'Color',slate);

ylabel(axB, ...
    'Probability density', ...
    'FontSize',8.5, ...
    'Color',slate);

set(axB, ...
    'FontSize',8, ...
    'LineWidth',0.8, ...
    'XColor',slate, ...
    'YColor',slate);

grid(axB,'on');
axB.GridAlpha = 0.12;

text(axB, ...
    0.96, ...
    0.89, ...
    sprintf('Median\n%.4g Pa',medDP), ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'FontSize',8, ...
    'FontWeight','bold', ...
    'Color',gold, ...
    'BackgroundColor',white, ...
    'Margin',4);

text(axB, ...
    0.96, ...
    0.71, ...
    sprintf('5–95%% range\n%.4g–%.4g Pa',p05,p95), ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'FontSize',7.5, ...
    'Color',navy, ...
    'BackgroundColor',white, ...
    'Margin',4);

%% ========================================================================
% PANEL C — ARCHITECTURE COMPARISON
% ========================================================================

axC = nexttile(layout,3);
hold(axC,'on');
box(axC,'on');

title(axC, ...
    'C   ARCHITECTURE COMPARISON', ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'Color',navy);

subtitle(axC, ...
    {'Independent normalization to each architecture median', ...
     '3 mm porous land  |  1 mm × 1 mm square flow channel'}, ...
    'FontSize',8.1, ...
    'Color',slate);

% Velocity sweep for relative response-shape comparison.
v = logspace(-4,-1,250);

%% Nominal porous baseline

k0 = ...
    (df0^2 * eps0^3) / ...
    (180 * (1-eps0)^2);

DP_baseline = ...
    mu0 .* L0 .* v ./ k0;

%% Nominal square-channel response

Re = ...
    rho .* v .* Dh ./ mu0;

f_D = ...
    fRe ./ Re;

DP_channel = ...
    f_D .* ...
    (L0./Dh) .* ...
    (rho .* v.^2 ./ 2);

%% Nominal porous-land response

DP_land = ...
    mu0 .* land0 .* v ./ k0;

%% Simplified parallel-path hydraulic surrogate

R_land = ...
    DP_land ./ v;

R_channel = ...
    DP_channel ./ v;

R_eff = ...
    1 ./ ...
    (1./R_land + 1./R_channel);

DP_assisted_nominal = ...
    R_eff .* v;

%% Channel-assisted Monte Carlo

% The channel hydraulic path length is assumed to follow the same
% nominal 3 mm architectural length as the porous electrode path.
% Its +/-10% uncertainty is therefore represented using L_range.

mu_chan = ...
    mu_range(1) + ...
    diff(mu_range).*rand(N_CHAN,1);

eps_chan = ...
    eps_range(1) + ...
    diff(eps_range).*rand(N_CHAN,1);

df_chan = ...
    df_range(1) + ...
    diff(df_range).*rand(N_CHAN,1);

L_chan = ...
    L_range(1) + ...
    diff(L_range).*rand(N_CHAN,1);

% Porous-land resistance.
k_chan = ...
    (df_chan.^2 .* eps_chan.^3) ./ ...
    (180 .* (1-eps_chan).^2);

R_land_chan = ...
    mu_chan .* land0 ./ k_chan;

% Square-channel Reynolds number.
Re_chan = ...
    rho .* v_screen .* Dh ./ mu_chan;

% Darcy friction factor using the square-channel laminar relation.
f_chan = ...
    fRe ./ Re_chan;

% Channel pressure drop.
DP_channel_chan = ...
    f_chan .* ...
    (L_chan./Dh) .* ...
    (rho .* v_screen.^2 ./ 2);

% Channel hydraulic resistance.
R_channel_chan = ...
    DP_channel_chan ./ v_screen;

% Parallel-path hydraulic resistance.
R_eff_chan = ...
    1 ./ ...
    (1./R_land_chan + 1./R_channel_chan);

% Channel-assisted screening metric.
DP_assisted_mc = ...
    R_eff_chan .* v_screen;

% Channel-assisted statistics.
medDP_chan = median(DP_assisted_mc);

p05_chan = prctile(DP_assisted_mc,5);

p95_chan = prctile(DP_assisted_mc,95);

%% Independent normalization

baseline_norm = ...
    DP_baseline ./ median(DP_baseline);

assisted_norm = ...
    DP_assisted_nominal ./ median(DP_assisted_nominal);

semilogx(axC, ...
    v, ...
    baseline_norm, ...
    'Color',blue, ...
    'LineWidth',2.2);

semilogx(axC, ...
    v, ...
    assisted_norm, ...
    '--', ...
    'Color',teal, ...
    'LineWidth',2.2);

yline(axC, ...
    1, ...
    ':', ...
    'Color',slate, ...
    'LineWidth',1.0);

xlabel(axC, ...
    'Characteristic flow velocity (m/s)', ...
    'FontSize',8.5, ...
    'Color',slate);

ylabel(axC, ...
    'Normalized pressure-drop metric', ...
    'FontSize',8.5, ...
    'Color',slate);

legend(axC, ...
    {'In-plane baseline','Channel-assisted surrogate'}, ...
    'Location','northwest', ...
    'FontSize',7.5, ...
    'Box','off');

set(axC, ...
    'FontSize',8, ...
    'LineWidth',0.8, ...
    'XColor',slate, ...
    'YColor',slate);

grid(axC,'on');
axC.GridAlpha = 0.12;

text(axC, ...
    0.97, ...
    0.10, ...
    'Relative model response', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'FontSize',7.0, ...
    'Color',slate, ...
    'BackgroundColor',white, ...
    'Margin',3);

%% ========================================================================
% PANEL D — PARAMETER SENSITIVITY
% ========================================================================

axD = nexttile(layout,4);
hold(axD,'on');
box(axD,'on');

title(axD, ...
    'D   PARAMETER SENSITIVITY', ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'Color',navy);

subtitle(axD, ...
    sprintf(['Pearson correlation with log_{10} pressure-drop ', ...
             'screening metric | %d samples'],N_SENS), ...
    'FontSize',8.2, ...
    'Color',slate);

% Independent uniform sampling over stated uncertainty ranges.
mu_sens = ...
    mu_range(1) + ...
    diff(mu_range).*rand(N_SENS,1);

eps_sens = ...
    eps_range(1) + ...
    diff(eps_range).*rand(N_SENS,1);

df_sens = ...
    df_range(1) + ...
    diff(df_range).*rand(N_SENS,1);

L_sens = ...
    L_range(1) + ...
    diff(L_range).*rand(N_SENS,1);

% Permeability.
k_sens = ...
    (df_sens.^2 .* eps_sens.^3) ./ ...
    (180 .* (1-eps_sens).^2);

% Baseline pressure-drop response.
DP_sens = ...
    mu_sens .* L_sens .* v_screen ./ k_sens;

% Log transformation used for sensitivity analysis.
response = log10(DP_sens);

% Pearson correlations.
corr_mu = corr(response,mu_sens);

corr_eps = corr(response,eps_sens);

corr_df = corr(response,df_sens);

corr_L = corr(response,L_sens);

corr_values = ...
    [corr_mu corr_eps corr_df corr_L];

param_names = { ...
    'Viscosity', ...
    'Porosity', ...
    'Fiber diameter', ...
    'Electrode thickness'};

ypos = 1:4;

barh(axD, ...
    ypos, ...
    corr_values, ...
    0.58, ...
    'FaceColor',blue, ...
    'EdgeColor','none');

xline(axD, ...
    0, ...
    '-', ...
    'Color',slate, ...
    'LineWidth',0.9);

yticks(axD,ypos);
yticklabels(axD,param_names);

xlabel(axD, ...
    'Pearson correlation coefficient', ...
    'FontSize',8.5, ...
    'Color',slate);

xlim(axD,[-1 1]);

set(axD, ...
    'YDir','reverse', ...
    'FontSize',8, ...
    'LineWidth',0.8, ...
    'XColor',slate, ...
    'YColor',slate);

grid(axD,'on');
axD.GridAlpha = 0.12;

for i = 1:numel(corr_values)

    r = corr_values(i);

    if r >= 0.15

        x_text = r - 0.035;
        align = 'right';
        txt_color = white;

    elseif r > 0

        x_text = r + 0.035;
        align = 'left';
        txt_color = navy;

    elseif r <= -0.15

        x_text = r + 0.035;
        align = 'left';
        txt_color = white;

    else

        x_text = r - 0.035;
        align = 'right';
        txt_color = navy;

    end

    text(axD, ...
        x_text, ...
        ypos(i), ...
        sprintf('%+.2f',r), ...
        'HorizontalAlignment',align, ...
        'VerticalAlignment','middle', ...
        'FontSize',8, ...
        'FontWeight','bold', ...
        'Color',txt_color, ...
        'Clipping','on');

end

%% ========================================================================
% FIGURE FOOTER
% ========================================================================

footer_text = sprintf( ...
    ['HIFE | %s | Author: %s | %s | Seed = %d | ', ...
     'Analytical/computational screening; compression, entrance, ', ...
     'gas-phase, and clogging effects excluded.'], ...
    SCRIPT_NAME, ...
    AUTHOR, ...
    DATE_STR, ...
    SEED);

annotation(fig, ...
    'textbox',[0.06 0.006 0.88 0.018], ...
    'String',footer_text, ...
    'EdgeColor','none', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontSize',6.5, ...
    'Color',slate);

%% ========================================================================
% RENDER / EXPORT
% ========================================================================

drawnow;

set(fig, ...
    'Units','pixels', ...
    'Position',[100 100 1800 1200]);

drawnow;

% PNG for LaTeX / submission.
png_file = ...
    'IMG_1472.jpeg';

% Export high-resolution PNG first.
png_temp = ...
    'HIFE_Figure2_Hydraulic_MonteCarlo.png';

exportgraphics( ...
    fig, ...
    png_temp, ...
    'Resolution',400);

% Export vector PDF.
drawnow;

pdf_file = ...
    'HIFE_Figure2_Hydraulic_MonteCarlo.pdf';

exportgraphics( ...
    fig, ...
    pdf_file, ...
    'ContentType','vector');

%% ========================================================================
% CONSOLE SUMMARY
% ========================================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('HIFE HYDRAULIC DESIGN-SPACE SCREENING\n');
fprintf('============================================================\n');

fprintf('\nIdentification\n');
fprintf('  Author:                 %s\n',AUTHOR);
fprintf('  Date:                   %s\n',DATE_STR);
fprintf('  Random seed:            %d\n',SEED);

fprintf('\nMonte Carlo settings\n');
fprintf('  Baseline:               %d samples\n',N_BASE);
fprintf('  Channel-assisted:       %d samples\n',N_CHAN);
fprintf('  Sensitivity:            %d samples\n',N_SENS);

fprintf('\nNominal hydraulic inputs\n');
fprintf('  Viscosity:              %.3g Pa*s\n',mu0);
fprintf('  Density:                %.3g kg/m^3\n',rho);
fprintf('  Porosity:               %.3f\n',eps0);
fprintf('  Fiber diameter:         %.3g m\n',df0);
fprintf('  Electrode thickness:    %.3g m\n',L0);
fprintf('  Cell area:              %.3g m^2\n',Acell);
fprintf('  Porous land:            %.3g m\n',land0);
fprintf('  Square channel:         %.3g x %.3g m\n',channel0,channel0);
fprintf('  Hydraulic diameter:     %.3g m\n',Dh);
fprintf('  f_D*Re_Dh:              %.2f\n',fRe);
fprintf('  Screening velocity:     %.3g m/s\n',v_screen);

fprintf('\nBaseline hydraulic screening\n');
fprintf('  Median:                 %.4g Pa\n',medDP);
fprintf('  5th percentile:         %.4g Pa\n',p05);
fprintf('  95th percentile:        %.4g Pa\n',p95);

fprintf('\nChannel-assisted surrogate\n');
fprintf('  Median:                 %.4g Pa\n',medDP_chan);
fprintf('  5th percentile:         %.4g Pa\n',p05_chan);
fprintf('  95th percentile:        %.4g Pa\n',p95_chan);

fprintf('\nSensitivity correlations\n');
fprintf('  Viscosity:              %+0.3f\n',corr_mu);
fprintf('  Porosity:               %+0.3f\n',corr_eps);
fprintf('  Fiber diameter:         %+0.3f\n',corr_df);
fprintf('  Electrode thickness:    %+0.3f\n',corr_L);

fprintf('\nModel scope\n');
fprintf('  Evidence type:          Analytical/computational\n');
fprintf('  Experimental data:      None\n');
fprintf('  CFD:                    None\n');
fprintf('  Compression:            Excluded\n');
fprintf('  Entrance effects:       Excluded\n');
fprintf('  Gas phase:              Excluded\n');
fprintf('  Clogging:               Excluded\n');

fprintf('\nInterpretation boundary\n');
fprintf('  Channel result:         Simplified hydraulic surrogate\n');
fprintf('  Absolute pump savings:  Not established\n');
fprintf('  Electrochemical gain:   Not established\n');
fprintf('  Experimental validation: Required\n');

fprintf('\nExported files\n');
fprintf('  High-resolution PNG:    %s\n',png_temp);
fprintf('  Vector PDF:             %s\n',pdf_file);

fprintf('============================================================\n');
fprintf('Export complete.\n');
fprintf('============================================================\n\n');
